config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "users#index"

  resources :users, only: [:index, :show, :destroy] do
    namespace :api do
      namespace :v1 do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy] do
        resources :replies, only: [:new, :create]
      end
    end
  end
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_one_attached :photo

  attribute :posts_counter, default: 0
  attribute :role, :string

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_save :set_posts_counter

  def set_posts_counter
    self.posts_counter = posts.count
  end

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def destroy
    super
    flash[:notice] = 'You have been signed out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = Post
    @posts = @user.posts.limit(3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.posts.destroy_all
    @user.destroy
    redirect_to users_path, notice: 'User deleted successfully.'
  end

  def sign_out_user
    sign_out current_user
    redirect_to root_path
  end
end

app/views/users/index.html.erb
<% if @users.blank? %>
  <p>There are not any users currently in the system.</p>
<% else %>
  <h1>All users</h1>
  <main>
    <ul class="users_list">
      <% @users.each do |user| %>
        <li class="list_item">
          <a class="link" href="/users/<%= user.id %>">
            <div class="photo">
              <% if user.photo.attached? %>
              <%= image_tag url_for(user.photo), class: "profile_img", alt: 'profile photo' %>
              <% else %>
                <%= image_tag "https://tse4.mm.bing.net/th?id=OIP.VwOipFm0fDDr_KOzoyrgVwAAAA&pid=Api&P=0&h=180",
                class: "profile_img" %>
              <% end %>
            </div>
            <div class="user_name">
              <h3><%= user.name %></h3>
              <p>Number of posts:
                <%= user.posts.count %></p>
            </div>
          </a>
        </li>
      <% end %>
    </ul>
  </main>
<% end %>

app/views/users/show.html.erb
<main>
  <div class="profile_wrap">
    <div class="photo">
      <% if @user.photo.present? %>
        <%= image_tag @user.photo,  class: "profile_img" %>
      <% else %>
        <%= image_tag "https://tse4.mm.bing.net/th?id=OIP.VwOipFm0fDDr_KOzoyrgVwAAAA&pid=Api&P=0&h=180",
        class: "profile_img" %>
      <% end %>
    </div>
    <div class="user_name">
      <h3><%= @user.name %></h3>
      <p>Number of posts:
        <%= @user.posts.count %></p>
    </div>
  </div>
  <div class="bio">
    <h4>Bio</h4>
    <br/>
    <p><%= @user.bio %></p>
  </div>
  <% if @user.posts.blank? %>
      <p>There are not any posts at the moment!</p>
  <% else %>
    <ul class="cards-container">
      <% @user.recent_posts.each do |post| %>
        <li class="post">
          <%= link_to user_post_path(@user, post) do %>
            <div class="image-wrapper">
              <% if post.image.present? %>
                <%= image_tag url_for(post.image), class: "post-img", alt: "post" %>
              <% else %>
                <%= image_tag "https://www.pngkey.com/png/detail/233-2332677_image-500580-placeholder-transparent.png",
                class: "post-img",
                alt: "post" %>
              <% end %>
            </div>
            <div class="post-footer">
              <div class="post-date-wrap">
                <h4>Post #<%= post.id %></h4>
                <h4><%= post.created_at %></h4>
              </div>
              <div class="post-title-wrap">
                <h4><%= post.title %></h4>
              </div>
              <div class="post-text-wrap">
                <p><%= truncate(post.text, length: 30) %></p>
                <p class="read-more">Read more</p>
              </div>
              <div class="post-likes-wrap">
                <p class="float">Comments:<%= post.comments.count %></p>
                <p class="float">Likes:
                  <%= post.likes.count %></p>
              </div>
            </div>

          <% end %>
        </li>
      <% end %>
    </ul>
  <%end%>
  <% if @user.posts.count > 0 %>
    <div class="btn_container">
      <%= link_to "See all posts", user_posts_path(@user), class: "btns" %>
      <% if user_signed_in? %>
        <% if can? :create, @post%>
          <%= link_to "New Post", new_user_post_path(@user), class: "btns" %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="btn_container">
      <% if user_signed_in? %>
        <% if can? :create, @post %>
          <%= link_to "New Post", new_user_post_path(@user), class: "btns" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</main>