config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "users#index"

  resources :users, only: [:index, :show, :destroy] do
    namespace :api do
      namespace :v1 do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy] do
        resources :replies, only: [:new, :create]
      end
    end
  end
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  has_one_attached :image
  after_save :update_user_posts_counter

  attribute :comments_counter, default: 0
  attribute :likes_counter, default: 0

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.last(5)
  end

  private

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        user = User.find(params[:user_id])
        posts = user.posts.includes(:author, :comments)

        render json: posts
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  # before_action :set_post, only: [:index, :show, :edit, :update, :destroy]
  load_and_authorize_resource # This line will automatically authorize each action based on the Ability class

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments)

    respond_to do |format|
      format.html { render :index }
    end
  end

  def show
    @post = @user.posts.includes(:author, :comments).find(params[:id])
  end

  def new
    @post = Post.new(author: current_user)
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(user_id: current_user.id)
    else
      render :new
    end
  end

  def destroy
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy

    redirect_to user_posts_path(user_id: @user.id)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  # def set_post
  #   @post = current_user.posts.find(params[:id])
  # end

  def post_params
    params.require(:post).permit(:title, :text, :image, :posted_date)
  end
end

app/views/Posts/index.html.erb
<main>
    <div id="list_item" class="profile_wrap">
        <div class="photo">
            <% if @user.photo.present? %>
                <%= image_tag @user.photo, class: 'profile_img' %>
              <% else %>
                <%= image_tag 'https://www.pngkey.com/png/detail/233-2332677_image-500580-placeholder-transparent.png', class: 'profile_img' %>
              <% end %>
        </div>
        <div class="user_name">
           <h4><%= @user.name %></h4>
           <p>Number of posts: <%= @user.posts.count %></p>
        </div>
    </div>
    <% if @posts.blank? %>
    <p>There are not any post currently for this author.</p>
    <a href="/users/<%=@user.id%>/posts/new">Add New Post </a>
    <% else %>
        <ul id="list" class="cards-container">
        <% @posts.each do |post| %>
        <li class="post">
            <%= link_to user_post_path(@user, post) do %>
              <div class="image-wrapper">
                <% if post.image.attached? %>
                  <%= image_tag url_for(post.image), class: 'post-img', alt: 'post' %>
                <% else %>
                  <%= image_tag 'https://www.pngkey.com/png/detail/233-2332677_image-500580-placeholder-transparent.png', class: 'post-img', alt: 'post' %>
                <% end %>
              </div>
              <div class="post-footer">
                <div class="post-date-wrap">
                  <h4>Post #<%= post.id %></h4>
                  <h4><%= post.created_at%></h4>
                </div>
                <div class="post-title-wrap">
                  <h4><%= post.title %></h4>
                </div>
                <div class="post-text-wrap">
                  <p><%= truncate(post.text, length: 30) %></p>
                  <p class="read-more">Read more</p>
                </div>
                <div class="post-likes-wrap">
                   <p class="float">Comments:<%= post.comments.count %></p>
                   <p class="float">Likes: <%= post.likes.count %></p>
                </div>
              </div>
                 
      
            <% end %>
        </li>
        <% end %>
        </ul>
      <% if @user.posts.count > 9 %>
    <div class="btn_container">
      <%= link_to 'Back', user_path(@user) %>
      <%= link_to 'New Post', new_user_post_path(@user) %>
      <%= link_to 'Next'%>
    </div>
    <% else %>
   <div class="btn_container">
      <%= link_to 'Back', user_path(@user) %>
      <%= link_to 'New Post', new_user_post_path(@user) %>
    </div>
    <% end %>
  <% end %>
</main>

app/views/Posts/new.html.erb
<h1>New Post</h1>
   <%= form_with model: @post, url: user_posts_path(user_id: current_user.id), method: :post do |f| %>


  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Titel" %>
  </div>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area :text, placeholder: "Description" %>
  </div>
  <div class="field">
      <%= f.file_field :image, placeholder: "Upload image" %>
  </div>

  <%= f.submit "Add post" %>
<% end %>

app/views/Posts/show.html.erb
<main>
    <div class="detail">

          <div class="profile_wrap">
        <div class="photo">
             <% if @user.photo.present? %>
                <%= image_tag @user.photo, class: 'profile_img' %>
              <% else %>
                <%= image_tag 'https://tse4.mm.bing.net/th?id=OIP.VwOipFm0fDDr_KOzoyrgVwAAAA&pid=Api&P=0&h=180', class: 'profile_img' %>
              <% end %>
        </div>
        <div class="user_name">
            <h3><%= @user.name %></h3>
            <p>Post# <%= @post.id %></p>
        </div>
    </div>
        <div class="detail_text">
            <p><%= @post.text %></p>
        </div>
        <article class="post post_detail">
              <div class="detail_image_wrapper">
                <% if @post.image.present? %>
                  <%= image_tag @post.image, class: 'post-img', alt: 'post' %>
                <% else %>
                  <%= image_tag 'https://www.pngkey.com/png/detail/233-2332677_image-500580-placeholder-transparent.png', class: 'post-img', alt: 'post' %>
                <% end %>
              </div>
              <div class="post-footer">
                <div class="post-title-wrap">
                  <h4><%= @post.title %></h4>
                </div>
                <div class="likes_count">
                   <p>Comments:<%= @post.comments.count %>, Likes: <%= @post.likes.count %></p>
                </div>
                <div class="btn_container">
      <% if can? :destroy,  @post %>
        <%= button_to 'Delete', user_post_path(@user, @post), method: :delete, class: "like-btn delete" %>
      <% end %>
      <%= button_to 'Comment', new_user_post_comment_path(@user, @post), method: :get, class: "like-btn" %>
      <% if current_user.likes.exists?(post: @post) %>
        <%= button_to 'Unlike ', user_post_like_path(user_id: @user.id, post_id: @post.id, id: current_user.likes.find_by(post: @post).id), method: :delete, class: "like-btn" %>
       
    <% else %>
      <%= button_to 'Like', user_post_likes_path(user_id: current_user.id, post_id: @post.id), method: :post, class: "like-btn" %>
    <% end %>
  </div>
              </div>
        </article>
    </div>
    <ul class="detail_comments">
        <% @post.comments.each do |comment| %>
        <li class="comment">
          <div class="photo comment_photo">
             <% if @user.photo.present? %>
                <%= image_tag @user.photo, class: 'profile_img' %>
              <% else %>
                <%= image_tag 'https://tse4.mm.bing.net/th?id=OIP.VwOipFm0fDDr_KOzoyrgVwAAAA&pid=Api&P=0&h=180', class: 'profile_img' %>
              <% end %>
        </div>
          <div class="comment_wrap">
            <h3> <%= comment.author.name %></h3> 
            <p><%= comment.text%></p>
            <div class="reply-btn-wrap">
              <% if can? :destroy, comment %>
                <%= button_to 'Delete', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
              <%end%>
              <%= button_to 'Reply', new_user_post_comment_reply_path(@user, @post, comment), method: :get, class: "like-btn" %>
            </div>
            <%# Replies %>
            <ul class="replies">
     <% comment.replies.each do |r| %>
        <li class="comment reply">
          <div class="photo comment_photo">
             <% if @user.photo.present? %>
                <%= image_tag @user.photo, class: 'profile_img' %>
              <% else %>
                <%= image_tag 'https://tse4.mm.bing.net/th?id=OIP.VwOipFm0fDDr_KOzoyrgVwAAAA&pid=Api&P=0&h=180', class: 'profile_img' %>
              <% end %>
        </div>
          <div class="comment_wrap">
           <h3> <%= r.author.name %></h3> 
           <p><%= r.text%></p>
          </div>
          </li>
        <% end %>
  </ul>
          </div>
          </li>
        <% end %>
  </ul>
</main>