config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "users#index"

  resources :users, only: [:index, :show, :destroy] do
    namespace :api do
      namespace :v1 do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:new, :create, :destroy] do
        resources :replies, only: [:new, :create]
      end
    end
  end
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header>
      <nav class="nav">
        <%= link_to 'Home', users_path, class: 'nav_link'%>
        <% if user_signed_in? %>
          <%= link_to 'New Post', new_user_post_path(user_id: current_user.id), method: :get, class: 'nav_link' %>
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav_link' %>
          <%= link_to "Logout", sign_out_user_path, method: :get, class: 'nav_link' %>
          <span class="nav_link"> Logged in as <strong><%= current_user.email %></strong></span>.
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav_link'  %>
          <%= link_to "Login", new_user_session_path, :class => 'nav_link'  %>
        <% end %>
         
      </nav>
   </header>
   <div class="notice_wrap">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <%= yield %>
  </body>
</html>